## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'opencv'

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_opencv' #to modify
description = 'plugin to use camera instrumented using the opencv library'

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cnrs.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0', 'opencv-python']
